### ISSUE TITLE
Resize only selected rows/columns

### ISSUE THREAD

**Issue by espilioto** [andreinitescu/GridSplitterApp#1]
Hello!

I just found this project, it's great because the ability to resize grids is really something essential.
I have a question though and I wonder if I am missing something.

Imagine a grid with these row definitions:
```
<RowDefinition Height="2*" />
<RowDefinition Height="12*"/>
<RowDefinition Height="Auto"/>
<RowDefinition Height="16*"/>
<RowDefinition Height="1*"/>
```
You can guess from the stars that I got a logo/title, main content in a list, the separator, item details and a status bar.

Is there a way to just resize the two main rows instead of all of them?

Thanks.

**Comment by andreinitescu** [comment]
Not sure I understand. Since all your rows heights are proportional (you're using *), when you're dragging the splitter isn't it supposed to update rows height too?

**Comment by espilioto** [comment]
Yes, it is and yes it does.
It resizes all rows proportionally.

What I am asking is if it can resize _only_ specific rows, in my case just 1 and 3 (where the content is).

Thanks for the quick reply 👍

**Comment by andreinitescu** [comment]
In that case you need to design the rows such way:

```
<RowDefinition Height="Auto" />
<RowDefinition Height="12*"/>
<RowDefinition Height="Auto"/>
<RowDefinition Height="16*"/>
<RowDefinition Height="Auto"/>

```

**Comment by espilioto** [comment]
Heh.
Yup, you are right, I was missing something after all =)

Thanks!
