### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by baldarama** [andreinitescu/GridSplitterApp#2]
hello i cant make it work, i thinkt that its becouse im using a newer version of xamarinForms, could you please helpme?
in 
public static readonly BindableProperty ControlTemplateProperty 
at line 13 in file GridSplitter.cs ths ide is suggesting me to add the word new 
public new static readonly BindableProperty ControlTemplateProperty
![image](https://user-images.githubusercontent.com/6646536/37357761-da1fb852-26ae-11e8-80d5-9ee78bfde2c3.png)

and in BindableProperty.Create<GridSplitter, DataTemplate>(...);
it says that Generic versions of Create() are no longer supported and deprecated. They will be removed soon
![image](https://user-images.githubusercontent.com/6646536/37357711-bcb31a48-26ae-11e8-8831-d5fc0b7e0766.png)

**Comment by andreinitescu** [comment]
What it means is you just need to use the non-template version. So you should just replace the `BindableProperty.Create<T>(...)` with the `BindableProperty.Create(...)`

**Comment by baldarama** [comment]
i let it like this
![image](https://user-images.githubusercontent.com/6646536/37362104-05bb8468-26ba-11e8-9eaa-5c96dc733c2c.png)
but the gridSplitter is newer rendered

**Comment by baldarama** [comment]
:O sorry, i just had to copy the <Application.Resources> ...</Application.Resources> to the page where i was trying to use the grid spliter lol

**Comment by andreinitescu** [comment]
@baldarama I just made a commit to make it work with latest Xamarin Forms.
Some things changed in Xamarin Forms, so I updated the implementation.
Let me know how it works for you.
